server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
      - source_labels: ['compose_service']
        regex: ''
        action: drop

    pipeline_stages:
      - match:
          selector: '{compose_service="app"}'
          stages:
            - json:
                expressions:
                  level: level
                  logger: logger_name
                  message: message
                  timestamp: '"@timestamp"'
                  traceId: traceId
                  spanId: spanId
            - labels:
                level:
                logger:
                traceId:
                spanId:
            - timestamp:
                source: timestamp
                format: '2006-01-02T15:04:05.000Z07:00'

      - match:
          selector: '{compose_service!="app"}'
          stages:
            - regex:
                expression: '(?i)(?P<level>DEBUG|INFO|WARN(?:ING)?|ERROR|FATAL|PANIC)'
            - labels:
                level:
